---
- name: Set the name of a sudo group
  set_fact:
    sudo_group: sudo

- name: Ensure all necessary groups are created
  group:
    name: "{{ item }}"
    state: present
  loop:
    - docker
    - samba
    - "{{ username }}"

- name: Ensure the non-root user is created
  user:
    name: "{{ username }}"
    password: "{{ password | password_hash('sha512') }}"
    groups:
      - "{{ sudo_group }}"
      - docker
      - users
    append: yes
    update_password: on_create

- name: Allow '{{ sudo_group }}' group to have passwordless sudo
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^%{{ sudo_group }}'
    line: '%{{ sudo_group }} ALL=(ALL) NOPASSWD: ALL'
    validate: '/usr/sbin/visudo -cf %s'

- name: Chmod the user home directory
  file:
    path: "/home/{{ username }}"
    state: directory
    mode: 0755
    owner: "{{ username }}"
    group: "{{ username }}"
    recurse: yes

- name: Suppress login messages
  file:
    name: /home/{{ username }}/.hushlogin
    mode: 0644
    state: touch
    owner: "{{ username }}"
    group: "{{ username }}"
    modification_time: preserve
    access_time: preserve

- name: Copy the public SSH key 
  authorized_key:
    user: "{{ username }}"
    state: present
    key: "{{ ssh_public_key }}"

- name: Disable cron e-mail notifications
  cron:
    name: MAILTO
    user: "{{ username }}"
    env: yes
    job: ""