---
- name: Install Python and python3-pip
  package:
    name:
      - python3
      - python3-pip
    state: present

- name: Install docker module for Python
  pip:
    name: 
      - docker
      - docker-compose

- name: Make sure that the all folders exists
  ansible.builtin.file:
    path: "{{ item }}"
    owner: "{{ username }}"
    group: "{{ username }}"
    state: directory
  loop:
    - "{{ docker_compose_dir }}"
    - "{{ docker_dir }}"
    - "{{ homer_assets_dir }}"

- name: Copy the template files
  template: 
    src: {{ item.src }}
    dest: "{{ item.dest }}"
  with_items:
    - src: templates/compose.yaml
      dest: "{{ docker_compose_dir }}/compose.yaml"
    - src: templates/homer_config.yaml
      dest: "{{ homer_assets_dir }}/config.yaml"

- name: Copy the homer config file
  template: 
    src: templates/homer_config.yaml
    dest: "{{ homer_assets_dir }}/config.yaml"

- name: Docker-compose up
  community.docker.docker_compose:
    project_src: "{{ docker_compose_dir }}"
